server:
  port: 9090

spring:
  h2:
    console:
      enabled: true

keycloak:
  realm: SpringBootKeycloak
  auth-server-url: http://localhost:8080/
  resource: login-api
  public-client: true
  bearer-only: true